### ISSUE TITLE
There are some _moderate_ vulnerabilities in `awesome-typed-sass-modules`.

### ISSUE THREAD

**Issue by ncochard** [Feiyang1/awesome-typed-sass-modules#9]
Hello

We are using `awesome-typed-sass-modules` in our project. And the command `npm audit` reveals that there are two vulnerabilities in this module.
https://www.npmjs.com/advisories/566
https://www.npmjs.com/advisories/598

This problem can easily be fixed...

According to https://registry.npmjs.org, `awesome-typed-sass-modules` has a dependency on `node-sass@4.9.0` which itself has a dependency on an old version of `hoek`. This is what is causing the issue.

I see that the problem has already been fixed in the source code in [GitHub](https://github.com/Feiyang1/awesome-typed-sass-modules). Indeed, the source code uses `node-sass@4.9.4`.

All you need to do to fix the vulnerabilities is to publish a new version of the package to npm.

```
npm version patch
npm publish
```

Best regards

Nicolas

**Comment by Feiyang1** [comment]
Thanks for the issue/reminder! I have published 1.1.5 with the fix.
